version: '3'

services:
  app:
    build: ./app
    image: app
    ports:
      - "8501:8501"
    networks:
    - deployml_network
    # volumes:
        # - ./app:/app

networks:
    deployml_network:
